# Tuition 1   
## Tutor: Chris D
## E-mail: C.Duan@westernsydney.edu.au

## Section 1: Basic Python

### (Strongly!!!) Recommend Learning Course for Python Programming: 
### berkeley CS61a   
### Web: https://cs61a.org/   
### (Strongly!!!) Recommend Reference book for Machine Learning: 
### << Probabilitic Machine Learning : An Introduction \>>
### Web: https://probml.github.io/pml-book/book1.html

### First Part
### Python Variables  

#### Variables are containers for storing data values. They are created when you assign a value to them. 
#### E.g: a = 5. 
#### Variables can contain letters, numbers, and underscores. 
#### Notice: Variables cannot start with a number and cannot use Python keywords.  (What is Python keywords, please search it !!!! ) 

#### Legal Examples:

In [35]:
name = "Chris"
age = 25 
school = "Western_Sydney_University" 

#### Type

#### Integer 

In [63]:
a = 5 
b = 1 
c = 12

#### Float 

In [66]:
a = 1.1 
b = 1.2 

In [70]:
type(a)

float

In [74]:
# Operations 
round(a)

1

#### String

In [83]:
message = "abcdefg" 
type(message) 

str

In [109]:
# operation for string  
print("hello" + " " + "Chris")
print("hello "*3) 
print(len("qwe "))

hello Chris
hello hello hello 
4


In [134]:
# String Formatting 
name = "Chris" 
age = 25
formatted = f"My name is {name}, I am {age} years old!" 
print(formatted) 

My name is Chris, I am 25 years old!


#### Boolean Type

In [140]:
print(5>3)

True


#### Collection Type
#### Lists - ordered, mutable collections 

In [202]:
## Sign: Starts with [ and ends as ] 
numbers = [1, 2, 3, 4, 5] 
a = ["qwe", 12, True] 

In [204]:
## Operations 
numbers.append(10)
print(numbers)

[1, 2, 3, 4, 5, 10]


In [206]:
numbers.insert(1, 100) 
# 1 refers to the position 
# Notice! In python, the number of array starts from 0 !!! 

In [208]:
numbers

[1, 100, 2, 3, 4, 5, 10]

In [210]:
numbers.remove(10)

In [212]:
numbers

[1, 100, 2, 3, 4, 5]

In [214]:
## Important !!!
## Slicing and Indexing for array 
print(numbers[0]) ## First item
print(numbers[-1]) ## Last one
print(numbers[1:3]) ## Items from 1 to 2 !!! Notice the last one 3 is not contained 
print(numbers[2:]) ## Items from 2 to end 

1
5
[100, 2]
[2, 3, 4, 5]


In [226]:
# Tuple 
## The main difference between tuple and list is that you can not change the items of tuple. 
a = (1,2,3,4)
## Wrong case:  a[1] = 10 
## Less memory cost, creating faster, accessing faster, better performance!

In [228]:
# Dictionary 
student = {
    "name": "Chris",
    "age": 25,
    "major": "Computer Science",
    "school": "CDMS"
} 

In [232]:
print(student["name"])

Chris


In [234]:
del student["school"] 

In [238]:
student['sex'] = "male"

In [240]:
student

{'name': 'Chris', 'age': 25, 'major': 'Computer Science', 'sex': 'male'}

In [244]:
student['major'] = "Mathematics" 
student

{'name': 'Chris', 'age': 25, 'major': 'Mathematics', 'sex': 'male'}

In [246]:
print(student.keys())  

dict_keys(['name', 'age', 'major', 'sex'])


In [248]:
print(student.values())

dict_values(['Chris', 25, 'Mathematics', 'male'])


In [252]:
# Get key-value pairs
print(student.items())

dict_items([('name', 'Chris'), ('age', 25), ('major', 'Mathematics'), ('sex', 'male')])


### Second Part 
### Control Structures

####  if-elif-else 

In [258]:
# Basic Example 
score = 85

if score >= 90:
    grade = "A"
elif score >= 80:
    grade = "B"
elif score >= 70:
    grade = "C"
elif score >= 60:
    grade = "D"
else:
    grade = "F"

In [260]:
grade 

'B'

In [262]:
## A little bit complex case 
## Nested Case 
age = 20
has_license = True
has_car = False

if age >= 18 and has_license:
    if has_car:
        print("Can drive own car")
    else:
        print("Can drive but needs a car")
elif age >= 16:
    print("Can get a learner's permit")
else:
    print("Too young to drive")

Can drive but needs a car


In [274]:
## Loop  
numbers = [1,2,3,4,5]
for i in numbers:
    print(i)
print("***********************************")
for i in range(len(numbers)):   # from 0 to 4 
    print(i + 1)

1
2
3
4
5
***********************************
1
2
3
4
5


In [276]:
## Interation for dictionary
student = {
    "name": "Chris",
    "age": 25,
    "major": "Computer Science",
    "school": "CDMS"
} 
for key in student:
    print(key)

name
age
major
school


In [290]:
for key,value in student.items():
    print(f"{key}: {value}")

name: Chris
age: 25
major: Computer Science
school: CDMS


In [292]:
## Loop
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


In [294]:
## Loop Control 
for i in range(10):
    if i == 3:
        continue  # Skip current iteration
    if i == 7:
        break     # Exit loop
    print(i)

0
1
2
4
5
6


#### Function 

In [297]:
# Simple function
def greet(name):
    return f"Hello,  I am {name}!"

In [307]:
greet("Chris")

'Hello,  I am Chris!'

In [313]:
# Function call
a = greet

In [319]:
# Function Parameters
def introduce(name, age=25, city="Sydney"):
    return f"I'm {name}, {age} years old, from {city}" 

In [321]:
introduce(name = "Chris")

"I'm Chris, 25 years old, from Sydney"

In [325]:
introduce(name = "Chris", age = 125)

"I'm Chris, 125 years old, from Sydney"

In [329]:
introduce(name = "Chris", city = "Parramatta")

"I'm Chris, 25 years old, from Parramatta"

In [333]:
introduce(name = "Chris", age = 25, city = "Parramatta")

"I'm Chris, 25 years old, from Parramatta"

In [337]:
## Motivation: How about the number of parameters is changed?
## Here we need to use the variable argument mechanism  
def all(*args):
    '''
    receive any number of parameters, and add them
    '''
    total = 0
    for num in args:
        total += num
    return total

In [345]:
all(1,2,3)

6

In [347]:
all(1,2,3,4,5,6)

21

In [349]:
### **kwargs: Receive all parameters and put them into a dictionary 
def examples(**kwargs):
    for key, value in kwargs.items():
        print(f"{key}: {value}")
examples(name="Alice", age=25, major="Computer Science")

name: Alice
age: 25
major: Computer Science


In [352]:
### Third Part 
### Numpy and Pandas

In [354]:
import numpy as np

In [356]:
import pandas as pd 

In [358]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([[1, 2, 3], [4, 5, 6]])

In [364]:
# Normal Special Arrays
zeros = np.zeros((3, 4))         
ones = np.ones((2, 3))          
full = np.full((2, 2), 7)      
identity = np.eye(3)              
random_arr = np.random.random((2, 3)) 

# Creating sequences
range_array = np.arange(0, 10, 2)  
linspace = np.linspace(0, 1, 5)    

In [370]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(a + b)
print(a - b)
print(a * b)
print(a**2) # power

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 1  4  9 16]


In [374]:
print(a[-1])

4


In [378]:
a = np.arange(12) 
print(a.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [382]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [386]:
np.vstack([arr1, arr2])

array([[1, 2, 3],
       [4, 5, 6]])

In [388]:
np.hstack([arr1, arr2])

array([1, 2, 3, 4, 5, 6])

In [390]:
import pandas as pd 

In [392]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
s3 = pd.Series({'x': 100, 'y': 200, 'z': 300})

In [424]:
#Access by position, Series is 1D data
print(s2.iloc[2])
#Access by index
print(s2['a'])
print(s2['a':'b'])
print(s2[s2>10])

30
10
a    10
b    20
dtype: int64
b    20
c    30
dtype: int64


In [498]:
# DataFrame - 2D data
data = [['Chris', 25, 'Sydney'], ['Bob', 30, 'London']]
data_frame = pd.DataFrame(data, columns=['Name', 'Age', 'City'])
data_frame

Name  Age    City
0  Chris   25  Sydney
1    Bob   30  London

In [500]:
data_frame.shape

(2, 3)

In [502]:
data_frame.columns.tolist()

['Name', 'Age', 'City']

In [504]:
data_frame.index.tolist()

[0, 1]

In [506]:
# First row
data_frame.iloc[0]

Name     Chris
Age         25
City    Sydney
Name: 0, dtype: object

In [508]:
# row by index 
data_frame.loc[0]

Name     Chris
Age         25
City    Sydney
Name: 0, dtype: object

In [510]:
# Conditional Selection 
data_frame[data_frame['Age']>25]

Name  Age    City
1  Bob   30  London

In [512]:
data_frame.loc[data_frame['Name'] == 'Chris', 'City'] = 'Parramatta'

In [514]:
data_frame

Name  Age        City
0  Chris   25  Parramatta
1    Bob   30      London

In [524]:
data_frame = data_frame.rename(columns = {'Name': 'name', 'Age': 'age'})

In [526]:
data_frame

name  age        City
0  Chris   25  Parramatta
1    Bob   30      London

In [530]:
data = pd.read_csv("car_data.csv")

In [532]:
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [534]:
data[(data['Selling_Price']>3.35) & (data['Present_Price'] < 10)]

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
1              sx4  2013           4.75           9.54       43000    Diesel   
2             ciaz  2017           7.25           9.85        6900    Petrol   
4            swift  2014           4.60           6.87       42450    Diesel   
5    vitara brezza  2018           9.25           9.83        2071    Diesel   
6             ciaz  2015           6.75           8.12       18796    Petrol   
..             ...   ...            ...            ...         ...       ...   
291           brio  2015           5.40           6.10       31427    Petrol   
292           jazz  2016           6.40           8.40       12000    Petrol   
294          amaze  2014           3.75           6.80       33019    Petrol   
297           brio  2015           4.00           5.90       60000    Petrol   
300           brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
1        Dealer       Manual      0  
2        Dealer       Manual      0  
4        Dealer       Manual      0  
5        Dealer       Manual      0  
6        Dealer       Manual      0  
..          ...          ...    ...  
291      Dealer       Manual      0  
292      Dealer       Manual      0  
294      Dealer       Manual      0  
297      Dealer       Manual      0  
300      Dealer       Manual      0  

[91 rows x 9 columns]

In [536]:
data['random'] = data['Selling_Price'] + data['Present_Price'] 

In [538]:
data.sort_values('Selling_Price').head(5)

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven  \
200    Bajaj Pulsar 150  2006           0.10           0.75       92233   
199      Honda CB Shine  2007           0.12           0.58       53000   
198  Bajaj Discover 125  2011           0.15           0.57       35000   
197    Honda CB twister  2010           0.16           0.51       33000   
196           Activa 3g  2008           0.17           0.52      500000   

    Fuel_Type Seller_Type Transmission  Owner  random  
200    Petrol  Individual       Manual      0    0.85  
199    Petrol  Individual       Manual      0    0.70  
198    Petrol  Individual       Manual      1    0.72  
197    Petrol  Individual       Manual      0    0.67  
196    Petrol  Individual    Automatic      0    0.69

In [544]:
for i in range(3,15,1):
    print(i)

3
4
5
6
7
8
9
10
11
12
13
14
